export enum driverName {
    Max_Verstappen = 'verstappen',
    Lewis_Hamilton = 'hamilton',
    Fernando_Alonso = 'alonso',
    Carlos_Sainz_Jr = 'sainz',
    Daniel_Ricciardo = 'ricciardo',
    Charles_Leclerc = 'leclerc',
    Sebastian_Vettel = 'vettel',
    Mick_Schumacher = 'mick',
    Sergio_Perez = 'perez',
    Kevin_Magnussen = 'magnussen',
    Lance_Stroll = 'stroll',
    Valtteri_Bottas = 'bottas',
    Lando_Norris = 'norris',


    Nico_Hülkenberg = 'hulkenberg',
    Robert_Kubica = 'kubica',
    Kimi_Räikkönen = 'raikkonen',
    Michael_Schumacher = 'schumacher',
    Ayrton_Senna = 'senna',    
    /* Marcus_Ericsson = 'ericsson',
    Rubens_Barrichello = 'barrichello',
    Felipe_Massa = 'massa',
    Jenson_Button = 'button',
    Alain_Prost = 'prost',
    Heikki_Kovalainen = 'kovalainen',
    Nico_Rosberg = 'rosberg',
    Pastor_Maldonado = 'maldonado',
    Niki_Lauda = 'lauda', 
    Toto_Wolff = 'wolff',
    Mattia_Binotto = 'binotto',
    Christian_Horner = 'horner',
    Susie_Wolff = 'susie' */
}
